version: "3.3"
services:
    gptjapi:
        image: ghcr.io/linuxserver/swag
        container_name: gptjapi
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - URL=${DOMAIN}
            - SUBDOMAINS=${SUBDOMAIN},
            - VALIDATION=http
            - STAGING=${DRYRUN}
            - ONLY_SUBDOMAINS=true
        volumes:
            - ${NGINX_PATH}:/config/nginx/proxy-confs/app.subdomain.conf
            - ${CERTS_PATH}:/config/etc/letsencrypt/
            - ${DNS_KEYS}:/config/keys/
        ports:
            - 443:443
            - 80:80
        restart: unless-stopped
        networks:
            - production
networks:
    production:
            